### ISSUE TITLE
php版本太低，我想用lnmp-1.6.tar.gz，可是build image出错

### ISSUE THREAD

**Issue by zengqingfu1442** [DuckLL/lnmp#1]
php版本太低，我想用lnmp-1.6.tar.gz（http://175.6.32.4:88/soft/lnmp/lnmp1.6.tar.gz），可是build image出错：
[WARNING]: Empty continuation line found in:
    RUN apt-fast update && apt-fast -y install    net-tools && apt-fast clean && wget http://soft.vpser.net/lnmp/lnmp1.6.tar.gz && tar -xvf ./lnmp1.6.tar.gz && cd lnmp1.6 && wget https://raw.githubusercontent.com/DuckLL/lnmp/master/install.conf && cat install.conf | ./install.sh && cd ../ && rm -rf lnmp1.6.tar.gz lnmp1.6 && wget https://raw.githubusercontent.com/DuckLL/lnmp/master/lnmp.sh -O /etc/my_init.d/lnmp.sh && chmod +x /etc/my_init.d/lnmp.sh
[WARNING]: Empty continuation lines will become errors in a future release.
...
/bin/sh: 1: apt-fast: not found
...

**Comment by DuckLL** [comment]
Because I just update the base image to Ubuntu 18.04, and there is no apt-fast in the image.
I think you can just replace "apt-fast" with "apt".
I will release new docker file and image soon.

**Comment by DuckLL** [comment]
The lnmp-1.6 doesn't support the auto-building.(The script doesn't exit after installing.)
I released a new web service project "micro_web". Maybe you can try that one.
